name: app-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.13
  - pip
  - numpy
  - pandas
  - pillow
  - imageio
  - opencv
  - shapely
  - geopandas
  - rasterio
  - fiona
  - gdal
  - pip:
      - streamlit==1.51.0
      - ultralytics==8.3.227
      - opencv-python-headless==4.8.1.78
      - pillow==12.0.0
      - imageio==2.37.2
